tasks:
  - init: |
      cd $GITPOD_REPO_ROOTS/website
      npm install
    command: |
      cd $GITPOD_REPO_ROOTS/website
      npm run start
  - command: gp ports await 3000 && gp preview $(gp url 3000)/
ports:
  - port: 3000
